CREATE OR REPLACE PROCEDURE GET_BY_EMPNUMBERS (IN I_EMP_ID_ARRAY STRING_ARRAY,
											   OUT O_STATUS CHAR(1),
											   OUT O_ERROR_CD INTEGER,
											   OUT O_ERROR_MSG VARCHAR(256)
												)
	DYNAMIC RESULT SETS 1
	LANGUAGE SQL
	
P1: BEGIN
	-- Declare cursor
	DECLARE EMP_CURSOR CURSOR WITH RETURN for
	  SELECT *
	  FROM IJUDY.EMPLOYEE 
	  WHERE EMPNO IN 
	  	(
	  		SELECT * FROM UNNEST(I_EMP_ID_ARRAY) AS (EMPNO)
	  	);
	
	SET O_STATUS = 'S';
	SET O_ERROR_CD = 100;
	SET O_ERROR_MSG = 'NO ERROR';
	
	OPEN EMP_CURSOR;
END P1